/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.mysql;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>taskcontrol</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.qopuir.taskcontrol.model.mysql.tables.records.ControlsScheduleRecord, java.lang.Long> IDENTITY_CONTROLS_SCHEDULE = Identities0.IDENTITY_CONTROLS_SCHEDULE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.mysql.tables.records.ControlsRecord> KEY_CONTROLS_PRIMARY = UniqueKeys0.KEY_CONTROLS_PRIMARY;
	public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.mysql.tables.records.ControlsScheduleRecord> KEY_CONTROLS_SCHEDULE_PRIMARY = UniqueKeys0.KEY_CONTROLS_SCHEDULE_PRIMARY;
	public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.mysql.tables.records.UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
	public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.mysql.tables.records.UsersControlsRecord> KEY_USERS_CONTROLS_PRIMARY = UniqueKeys0.KEY_USERS_CONTROLS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.qopuir.taskcontrol.model.mysql.tables.records.ControlsScheduleRecord, com.qopuir.taskcontrol.model.mysql.tables.records.ControlsRecord> CONTROLS_SCHEDULE_IBFK_1 = ForeignKeys0.CONTROLS_SCHEDULE_IBFK_1;
	public static final org.jooq.ForeignKey<com.qopuir.taskcontrol.model.mysql.tables.records.UsersControlsRecord, com.qopuir.taskcontrol.model.mysql.tables.records.UsersRecord> USERS_CONTROLS_IBFK_1 = ForeignKeys0.USERS_CONTROLS_IBFK_1;
	public static final org.jooq.ForeignKey<com.qopuir.taskcontrol.model.mysql.tables.records.UsersControlsRecord, com.qopuir.taskcontrol.model.mysql.tables.records.ControlsRecord> USERS_CONTROLS_IBFK_2 = ForeignKeys0.USERS_CONTROLS_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.qopuir.taskcontrol.model.mysql.tables.records.ControlsScheduleRecord, java.lang.Long> IDENTITY_CONTROLS_SCHEDULE = createIdentity(com.qopuir.taskcontrol.model.mysql.tables.ControlsSchedule.CONTROLS_SCHEDULE, com.qopuir.taskcontrol.model.mysql.tables.ControlsSchedule.CONTROLS_SCHEDULE.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.mysql.tables.records.ControlsRecord> KEY_CONTROLS_PRIMARY = createUniqueKey(com.qopuir.taskcontrol.model.mysql.tables.Controls.CONTROLS, com.qopuir.taskcontrol.model.mysql.tables.Controls.CONTROLS.NAME);
		public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.mysql.tables.records.ControlsScheduleRecord> KEY_CONTROLS_SCHEDULE_PRIMARY = createUniqueKey(com.qopuir.taskcontrol.model.mysql.tables.ControlsSchedule.CONTROLS_SCHEDULE, com.qopuir.taskcontrol.model.mysql.tables.ControlsSchedule.CONTROLS_SCHEDULE.ID);
		public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.mysql.tables.records.UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(com.qopuir.taskcontrol.model.mysql.tables.Users.USERS, com.qopuir.taskcontrol.model.mysql.tables.Users.USERS.USERNAME);
		public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.mysql.tables.records.UsersControlsRecord> KEY_USERS_CONTROLS_PRIMARY = createUniqueKey(com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS, com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS.USER_USERNAME, com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS.CONTROL_NAME);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.qopuir.taskcontrol.model.mysql.tables.records.ControlsScheduleRecord, com.qopuir.taskcontrol.model.mysql.tables.records.ControlsRecord> CONTROLS_SCHEDULE_IBFK_1 = createForeignKey(com.qopuir.taskcontrol.model.mysql.Keys.KEY_CONTROLS_PRIMARY, com.qopuir.taskcontrol.model.mysql.tables.ControlsSchedule.CONTROLS_SCHEDULE, com.qopuir.taskcontrol.model.mysql.tables.ControlsSchedule.CONTROLS_SCHEDULE.CONTROL_NAME);
		public static final org.jooq.ForeignKey<com.qopuir.taskcontrol.model.mysql.tables.records.UsersControlsRecord, com.qopuir.taskcontrol.model.mysql.tables.records.UsersRecord> USERS_CONTROLS_IBFK_1 = createForeignKey(com.qopuir.taskcontrol.model.mysql.Keys.KEY_USERS_PRIMARY, com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS, com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS.USER_USERNAME);
		public static final org.jooq.ForeignKey<com.qopuir.taskcontrol.model.mysql.tables.records.UsersControlsRecord, com.qopuir.taskcontrol.model.mysql.tables.records.ControlsRecord> USERS_CONTROLS_IBFK_2 = createForeignKey(com.qopuir.taskcontrol.model.mysql.Keys.KEY_CONTROLS_PRIMARY, com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS, com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS.CONTROL_NAME);
	}
}
