/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.mysql;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Taskcontrol extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 66493594;

	/**
	 * The singleton instance of <code>taskcontrol</code>
	 */
	public static final Taskcontrol TASKCONTROL = new Taskcontrol();

	/**
	 * No further instances allowed
	 */
	private Taskcontrol() {
		super("taskcontrol");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.qopuir.taskcontrol.model.mysql.tables.Controls.CONTROLS,
			com.qopuir.taskcontrol.model.mysql.tables.ControlsSchedule.CONTROLS_SCHEDULE,
			com.qopuir.taskcontrol.model.mysql.tables.Users.USERS,
			com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS);
	}
}
