DROP SCHEMA IF EXISTS TASKCONTROL;
CREATE SCHEMA TASKCONTROL;

DROP TABLE IF EXISTS TASKCONTROL.USER_CONTROLS;
DROP TABLE IF EXISTS TASKCONTROL.USERS;
DROP TABLE IF EXISTS TASKCONTROL.CONTROL_SCHEDULES;
DROP TABLE IF EXISTS TASKCONTROL.CONTROLS;

CREATE TABLE TASKCONTROL.USERS (
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	EMAIL VARCHAR(255),
	PRIMARY KEY(USERNAME)
);

CREATE TABLE TASKCONTROL.CONTROLS (
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(2000),
	PRIMARY KEY(NAME)
);

CREATE TABLE TASKCONTROL.USER_CONTROLS (
	USER_USERNAME VARCHAR(50),
	CONTROL_NAME VARCHAR(50),
	PRIMARY KEY(USER_USERNAME, CONTROL_NAME),
	FOREIGN KEY(USER_USERNAME) REFERENCES TASKCONTROL.USERS(USERNAME),
	FOREIGN KEY(CONTROL_NAME) REFERENCES TASKCONTROL.CONTROLS(NAME)
);

CREATE TABLE TASKCONTROL.CONTROL_SCHEDULES (
	ID IDENTITY,
	CONTROL_NAME VARCHAR(50),
	DESCRIPTION VARCHAR(2000),
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	SCHEDULE_STATUS VARCHAR(50),
	CRON VARCHAR(50),
	PRIMARY KEY(ID),
	FOREIGN KEY(CONTROL_NAME) REFERENCES TASKCONTROL.CONTROLS(NAME)
);