DROP SCHEMA IF EXISTS TASKCONTROL;
CREATE SCHEMA TASKCONTROL;

USE TASKCONTROL;

DROP TABLE IF EXISTS USER_CONTROLS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CONTROL_SCHEDULES;
DROP TABLE IF EXISTS CONTROLS;

CREATE TABLE USERS (
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	EMAIL VARCHAR(255),
	PRIMARY KEY(USERNAME)
);

CREATE TABLE CONTROLS (
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(2000),
	PRIMARY KEY(NAME)
);

CREATE TABLE USER_CONTROLS (
	USER_USERNAME VARCHAR(50),
	CONTROL_NAME VARCHAR(50),
	PRIMARY KEY(USER_USERNAME, CONTROL_NAME),
	FOREIGN KEY(USER_USERNAME) REFERENCES USERS(USERNAME),
	FOREIGN KEY(CONTROL_NAME) REFERENCES CONTROLS(NAME)
);

CREATE TABLE CONTROL_SCHEDULES (
	ID BIGINT AUTO_INCREMENT,
	CONTROL_NAME VARCHAR(50),
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	SCHEDULE_STATUS VARCHAR(50),
	CRON VARCHAR(50),
	PRIMARY KEY(ID),
	FOREIGN KEY(CONTROL_NAME) REFERENCES CONTROLS(NAME)
);