DROP TABLE IF EXISTS USERS_CONTROLS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(256),
	EMAIL VARCHAR(256),
	PRIMARY KEY(USERNAME)
);

INSERT INTO USERS(USERNAME, PASSWORD, EMAIL) VALUES ('demo', 'demo', 'demo@domain.com');

DROP TABLE IF EXISTS CONTROLS_SCHEDULE;
DROP TABLE IF EXISTS CONTROLS;

CREATE TABLE CONTROLS (
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(2000),
	PRIMARY KEY(NAME)
);

INSERT INTO CONTROLS(NAME, DESCRIPTION) VALUES ('PROJECTION_SEMANAL', 'Comprueba que los usuarios hayan imputado las horas en el projection hasta un determinado día de la semana. Envía un email a los que no lo hayan hecho.');
INSERT INTO CONTROLS(NAME, DESCRIPTION) VALUES ('PROJECTION_MENSUAL', 'Comprueba que los usuarios hayan imputado las horas de todo el mes en curso. Envía un email a los que no lo hayan hecho.');

CREATE TABLE USERS_CONTROLS (
	USER_USERNAME VARCHAR(50),
	CONTROL_NAME VARCHAR(50),
	PRIMARY KEY(USER_USERNAME, CONTROL_NAME),
	FOREIGN KEY(USER_USERNAME) REFERENCES USERS(USERNAME),
	FOREIGN KEY(CONTROL_NAME) REFERENCES CONTROLS(NAME)
);

CREATE TABLE CONTROLS_SCHEDULE (
	ID BIGINT AUTO_INCREMENT,
	CONTROL_NAME VARCHAR(50),
	START TIMESTAMP,
	END TIMESTAMP,
	STATUS VARCHAR(50),
	CRON VARCHAR(50),
	PRIMARY KEY(ID),
	FOREIGN KEY(CONTROL_NAME) REFERENCES CONTROLS(NAME)
);