DROP SCHEMA IF EXISTS TASKCONTROL;
CREATE SCHEMA TASKCONTROL DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE TASKCONTROL;

DROP TABLE IF EXISTS USER_CONTROLS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS CONTROL_SCHEDULE_PARAMS;
DROP TABLE IF EXISTS CONTROL_SCHEDULES;
DROP TABLE IF EXISTS CONTROL_PARAMS;
DROP TABLE IF EXISTS CONTROLS;

CREATE TABLE USERS (
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	EMAIL VARCHAR(255),
	PRIMARY KEY(USERNAME)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE CONTROLS (
	NAME VARCHAR(50),
	DESCRIPTION VARCHAR(2000),
	PRIMARY KEY(NAME)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE CONTROL_PARAMS (
	CONTROL_NAME VARCHAR(50),
	PARAM_NAME VARCHAR(50),
	REQUIRED BIT(1) DEFAULT 0,
	DEFAULT_VALUE VARCHAR(255),
	DESCRIPTION VARCHAR(2000),
	PRIMARY KEY(CONTROL_NAME, PARAM_NAME),
	FOREIGN KEY(CONTROL_NAME) REFERENCES CONTROLS(NAME)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE USER_CONTROLS (
	USER_USERNAME VARCHAR(50),
	CONTROL_NAME VARCHAR(50),
	PRIMARY KEY(USER_USERNAME, CONTROL_NAME),
	FOREIGN KEY(USER_USERNAME) REFERENCES USERS(USERNAME),
	FOREIGN KEY(CONTROL_NAME) REFERENCES CONTROLS(NAME)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE CONTROL_SCHEDULES (
	ID BIGINT AUTO_INCREMENT,
	CONTROL_NAME VARCHAR(50),
	DESCRIPTION VARCHAR(2000),
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	SCHEDULE_STATUS VARCHAR(50),
	CRON VARCHAR(50),
	PRIMARY KEY(ID),
	FOREIGN KEY(CONTROL_NAME) REFERENCES CONTROLS(NAME)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE CONTROL_SCHEDULE_PARAMS (
	CONTROL_SCHEDULE_ID BIGINT,
	CONTROL_NAME VARCHAR(50),
	PARAM_NAME VARCHAR(50),
	PARAM_VALUE VARCHAR(255) NOT NULL,
	PRIMARY KEY(CONTROL_SCHEDULE_ID, PARAM_NAME),
	FOREIGN KEY(CONTROL_NAME, PARAM_NAME) REFERENCES CONTROL_PARAMS(CONTROL_NAME, PARAM_NAME)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

------------------------------------
-- Spring Batch
------------------------------------

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_CONTEXT;
DROP TABLE IF EXISTS BATCH_STEP_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_PARAMS;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION;
DROP TABLE IF EXISTS BATCH_JOB_INSTANCE;

DROP TABLE IF EXISTS BATCH_STEP_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_EXECUTION_SEQ;
DROP TABLE IF EXISTS BATCH_JOB_SEQ;

CREATE TABLE BATCH_JOB_INSTANCE (
	JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE BATCH_JOB_EXECUTION (
	JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME DATETIME NOT NULL,
	START_TIME DATETIME DEFAULT NULL,
	END_TIME DATETIME DEFAULT NULL,
	STATUS VARCHAR(10),
	EXIT_CODE VARCHAR(100),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED DATETIME,
	constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
	references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	TYPE_CD VARCHAR(6) NOT NULL,
	KEY_NAME VARCHAR(100) NOT NULL,
	STRING_VAL VARCHAR(250),
	DATE_VAL DATETIME DEFAULT NULL,
	LONG_VAL BIGINT,
	DOUBLE_VAL DOUBLE PRECISION,
	IDENTIFYING CHAR(1) NOT NULL,
	constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE BATCH_STEP_EXECUTION (
	STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	START_TIME DATETIME NOT NULL,
	END_TIME DATETIME DEFAULT NULL,
	STATUS VARCHAR(10),
	COMMIT_COUNT BIGINT,
	READ_COUNT BIGINT,
	FILTER_COUNT BIGINT,
	WRITE_COUNT BIGINT,
	READ_SKIP_COUNT BIGINT,
	WRITE_SKIP_COUNT BIGINT,
	PROCESS_SKIP_COUNT BIGINT,
	ROLLBACK_COUNT BIGINT,
	EXIT_CODE VARCHAR(100),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED DATETIME,
	constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
	references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
	references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB CHARACTER SET=utf8, COLLATE=utf8_general_ci;

CREATE TABLE BATCH_STEP_EXECUTION_SEQ (
	ID BIGINT NOT NULL,
	UNIQUE_KEY CHAR(1) NOT NULL,
	constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=MYISAM CHARACTER SET=utf8, COLLATE=utf8_general_ci;

INSERT INTO BATCH_STEP_EXECUTION_SEQ values(0, '0');

CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
	ID BIGINT NOT NULL,
	UNIQUE_KEY CHAR(1) NOT NULL,
	constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=MYISAM CHARACTER SET=utf8, COLLATE=utf8_general_ci;

INSERT INTO BATCH_JOB_EXECUTION_SEQ values(0, '0');

CREATE TABLE BATCH_JOB_SEQ (
	ID BIGINT NOT NULL,
	UNIQUE_KEY CHAR(1) NOT NULL,
	constraint UNIQUE_KEY_UN unique (UNIQUE_KEY)
) ENGINE=MYISAM CHARACTER SET=utf8, COLLATE=utf8_general_ci;

INSERT INTO BATCH_JOB_SEQ values(0, '0');