/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord, java.lang.Long> IDENTITY_USERS = Identities0.IDENTITY_USERS;
	public static final org.jooq.Identity<com.qopuir.taskcontrol.model.h2.tables.records.ControlsRecord, java.lang.Long> IDENTITY_CONTROLS = Identities0.IDENTITY_CONTROLS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
	public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.ControlsRecord> CONSTRAINT_C = UniqueKeys0.CONSTRAINT_C;
	public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord> CONSTRAINT_5 = UniqueKeys0.CONSTRAINT_5;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord, java.lang.Long> IDENTITY_USERS = createIdentity(com.qopuir.taskcontrol.model.h2.tables.Users.USERS, com.qopuir.taskcontrol.model.h2.tables.Users.USERS.ID);
		public static org.jooq.Identity<com.qopuir.taskcontrol.model.h2.tables.records.ControlsRecord, java.lang.Long> IDENTITY_CONTROLS = createIdentity(com.qopuir.taskcontrol.model.h2.tables.Controls.CONTROLS, com.qopuir.taskcontrol.model.h2.tables.Controls.CONTROLS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord> CONSTRAINT_4 = createUniqueKey(com.qopuir.taskcontrol.model.h2.tables.Users.USERS, com.qopuir.taskcontrol.model.h2.tables.Users.USERS.ID);
		public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.ControlsRecord> CONSTRAINT_C = createUniqueKey(com.qopuir.taskcontrol.model.h2.tables.Controls.CONTROLS, com.qopuir.taskcontrol.model.h2.tables.Controls.CONTROLS.ID);
		public static final org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord> CONSTRAINT_5 = createUniqueKey(com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS, com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS.USER_ID, com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS.CONTROL_ID);
	}
}
