/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 73205631;

	/**
	 * The singleton instance of <code>PUBLIC</code>
	 */
	public static final Public PUBLIC = new Public();

	/**
	 * No further instances allowed
	 */
	private Public() {
		super("PUBLIC");
	}

	@Override
	public final java.util.List<org.jooq.Sequence<?>> getSequences() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getSequences0());
		return result;
	}

	private final java.util.List<org.jooq.Sequence<?>> getSequences0() {
		return java.util.Arrays.<org.jooq.Sequence<?>>asList(
			com.qopuir.taskcontrol.model.h2.Sequences.SYSTEM_SEQUENCE_1359A897_5690_43CD_9424_C2DD70AC7249,
			com.qopuir.taskcontrol.model.h2.Sequences.SYSTEM_SEQUENCE_D675D4C4_45B4_4047_907C_8E4381550CB0);
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			com.qopuir.taskcontrol.model.h2.tables.Users.USERS,
			com.qopuir.taskcontrol.model.h2.tables.Controls.CONTROLS,
			com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS);
	}
}
