/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_1359A897_5690_43CD_9424_C2DD70AC7249</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_1359A897_5690_43CD_9424_C2DD70AC7249 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_1359A897_5690_43CD_9424_C2DD70AC7249", com.qopuir.taskcontrol.model.h2.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_D675D4C4_45B4_4047_907C_8E4381550CB0</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_D675D4C4_45B4_4047_907C_8E4381550CB0 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_D675D4C4_45B4_4047_907C_8E4381550CB0", com.qopuir.taskcontrol.model.h2.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
