/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_A0F1C685_BA14_4F28_81E0_A7644A61077A</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_A0F1C685_BA14_4F28_81E0_A7644A61077A = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_A0F1C685_BA14_4F28_81E0_A7644A61077A", com.qopuir.taskcontrol.model.h2.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
