/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.USERS
	 */
	public static final com.qopuir.taskcontrol.model.h2.tables.Users USERS = com.qopuir.taskcontrol.model.h2.tables.Users.USERS;

	/**
	 * The table PUBLIC.CONTROLS
	 */
	public static final com.qopuir.taskcontrol.model.h2.tables.Controls CONTROLS = com.qopuir.taskcontrol.model.h2.tables.Controls.CONTROLS;

	/**
	 * The table PUBLIC.USERS_CONTROLS
	 */
	public static final com.qopuir.taskcontrol.model.h2.tables.UsersControls USERS_CONTROLS = com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS;

	/**
	 * The table PUBLIC.CONTROLS_SCHEDULE
	 */
	public static final com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule CONTROLS_SCHEDULE = com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule.CONTROLS_SCHEDULE;
}
