/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ControlsSchedule extends org.jooq.impl.TableImpl<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord> {

	private static final long serialVersionUID = 920136495;

	/**
	 * The singleton instance of <code>PUBLIC.CONTROLS_SCHEDULE</code>
	 */
	public static final com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule CONTROLS_SCHEDULE = new com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord> getRecordType() {
		return com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord.class;
	}

	/**
	 * The column <code>PUBLIC.CONTROLS_SCHEDULE.ID</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, java.lang.Long> ID = createField("ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>PUBLIC.CONTROLS_SCHEDULE.CONTROL_NAME</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, java.lang.String> CONTROL_NAME = createField("CONTROL_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>PUBLIC.CONTROLS_SCHEDULE.START</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, java.sql.Timestamp> START = createField("START", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>PUBLIC.CONTROLS_SCHEDULE.END</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, java.sql.Timestamp> END = createField("END", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>PUBLIC.CONTROLS_SCHEDULE.STATUS</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, java.lang.String> STATUS = createField("STATUS", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>PUBLIC.CONTROLS_SCHEDULE.CRON</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, java.lang.String> CRON = createField("CRON", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>PUBLIC.CONTROLS_SCHEDULE</code> table reference
	 */
	public ControlsSchedule() {
		this("CONTROLS_SCHEDULE", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.CONTROLS_SCHEDULE</code> table reference
	 */
	public ControlsSchedule(java.lang.String alias) {
		this(alias, com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule.CONTROLS_SCHEDULE);
	}

	private ControlsSchedule(java.lang.String alias, org.jooq.Table<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord> aliased) {
		this(alias, aliased, null);
	}

	private ControlsSchedule(java.lang.String alias, org.jooq.Table<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qopuir.taskcontrol.model.h2.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, java.lang.Long> getIdentity() {
		return com.qopuir.taskcontrol.model.h2.Keys.IDENTITY_CONTROLS_SCHEDULE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord> getPrimaryKey() {
		return com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_6;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord>>asList(com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.qopuir.taskcontrol.model.h2.tables.records.ControlsScheduleRecord, ?>>asList(com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_6E);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule as(java.lang.String alias) {
		return new com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule rename(java.lang.String name) {
		return new com.qopuir.taskcontrol.model.h2.tables.ControlsSchedule(name, null);
	}
}
