/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord> {

	private static final long serialVersionUID = 1463973163;

	/**
	 * The singleton instance of <code>PUBLIC.USERS</code>
	 */
	public static final com.qopuir.taskcontrol.model.h2.tables.Users USERS = new com.qopuir.taskcontrol.model.h2.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord> getRecordType() {
		return com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>PUBLIC.USERS.USERNAME</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord, java.lang.String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.USERS.PASSWORD</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord, java.lang.String> PASSWORD = createField("PASSWORD", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>PUBLIC.USERS.EMAIL</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord, java.lang.String> EMAIL = createField("EMAIL", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * Create a <code>PUBLIC.USERS</code> table reference
	 */
	public Users() {
		this("USERS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.USERS</code> table reference
	 */
	public Users(java.lang.String alias) {
		this(alias, com.qopuir.taskcontrol.model.h2.tables.Users.USERS);
	}

	private Users(java.lang.String alias, org.jooq.Table<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Users(java.lang.String alias, org.jooq.Table<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qopuir.taskcontrol.model.h2.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord> getPrimaryKey() {
		return com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersRecord>>asList(com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_4);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qopuir.taskcontrol.model.h2.tables.Users as(java.lang.String alias) {
		return new com.qopuir.taskcontrol.model.h2.tables.Users(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qopuir.taskcontrol.model.h2.tables.Users rename(java.lang.String name) {
		return new com.qopuir.taskcontrol.model.h2.tables.Users(name, null);
	}
}
