/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersControls extends org.jooq.impl.TableImpl<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord> {

	private static final long serialVersionUID = 1202613431;

	/**
	 * The singleton instance of <code>PUBLIC.USERS_CONTROLS</code>
	 */
	public static final com.qopuir.taskcontrol.model.h2.tables.UsersControls USERS_CONTROLS = new com.qopuir.taskcontrol.model.h2.tables.UsersControls();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord> getRecordType() {
		return com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord.class;
	}

	/**
	 * The column <code>PUBLIC.USERS_CONTROLS.USER_USERNAME</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord, java.lang.String> USER_USERNAME = createField("USER_USERNAME", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.USERS_CONTROLS.CONTROL_NAME</code>.
	 */
	public final org.jooq.TableField<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord, java.lang.String> CONTROL_NAME = createField("CONTROL_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.USERS_CONTROLS</code> table reference
	 */
	public UsersControls() {
		this("USERS_CONTROLS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.USERS_CONTROLS</code> table reference
	 */
	public UsersControls(java.lang.String alias) {
		this(alias, com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS);
	}

	private UsersControls(java.lang.String alias, org.jooq.Table<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord> aliased) {
		this(alias, aliased, null);
	}

	private UsersControls(java.lang.String alias, org.jooq.Table<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.qopuir.taskcontrol.model.h2.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord> getPrimaryKey() {
		return com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_5;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord>>asList(com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_5);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord, ?>>asList(com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_5D, com.qopuir.taskcontrol.model.h2.Keys.CONSTRAINT_5D5);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.qopuir.taskcontrol.model.h2.tables.UsersControls as(java.lang.String alias) {
		return new com.qopuir.taskcontrol.model.h2.tables.UsersControls(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.qopuir.taskcontrol.model.h2.tables.UsersControls rename(java.lang.String name) {
		return new com.qopuir.taskcontrol.model.h2.tables.UsersControls(name, null);
	}
}
