/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.mysql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersControlsRecord extends org.jooq.impl.UpdatableRecordImpl<com.qopuir.taskcontrol.model.mysql.tables.records.UsersControlsRecord> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1784016042;

	/**
	 * Setter for <code>taskcontrol.USERS_CONTROLS.USER_USERNAME</code>.
	 */
	public void setUserUsername(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>taskcontrol.USERS_CONTROLS.USER_USERNAME</code>.
	 */
	public java.lang.String getUserUsername() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>taskcontrol.USERS_CONTROLS.CONTROL_NAME</code>.
	 */
	public void setControlName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>taskcontrol.USERS_CONTROLS.CONTROL_NAME</code>.
	 */
	public java.lang.String getControlName() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS.USER_USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS.CONTROL_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getUserUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getControlName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersControlsRecord value1(java.lang.String value) {
		setUserUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersControlsRecord value2(java.lang.String value) {
		setControlName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersControlsRecord values(java.lang.String value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersControlsRecord
	 */
	public UsersControlsRecord() {
		super(com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS);
	}

	/**
	 * Create a detached, initialised UsersControlsRecord
	 */
	public UsersControlsRecord(java.lang.String userUsername, java.lang.String controlName) {
		super(com.qopuir.taskcontrol.model.mysql.tables.UsersControls.USERS_CONTROLS);

		setValue(0, userUsername);
		setValue(1, controlName);
	}
}
