/**
 * This class is generated by jOOQ
 */
package com.qopuir.taskcontrol.model.h2.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersControlsRecord extends org.jooq.impl.UpdatableRecordImpl<com.qopuir.taskcontrol.model.h2.tables.records.UsersControlsRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -1735934143;

	/**
	 * Setter for <code>PUBLIC.USERS_CONTROLS.USER_ID</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.USERS_CONTROLS.USER_ID</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.USERS_CONTROLS.CONTROL_ID</code>.
	 */
	public void setControlId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>PUBLIC.USERS_CONTROLS.CONTROL_ID</code>.
	 */
	public java.lang.Long getControlId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Long, java.lang.Long> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS.CONTROL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getControlId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersControlsRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersControlsRecord value2(java.lang.Long value) {
		setControlId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsersControlsRecord values(java.lang.Long value1, java.lang.Long value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsersControlsRecord
	 */
	public UsersControlsRecord() {
		super(com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS);
	}

	/**
	 * Create a detached, initialised UsersControlsRecord
	 */
	public UsersControlsRecord(java.lang.Long userId, java.lang.Long controlId) {
		super(com.qopuir.taskcontrol.model.h2.tables.UsersControls.USERS_CONTROLS);

		setValue(0, userId);
		setValue(1, controlId);
	}
}
